### ISSUE TITLE
[Draft] antd v5 final tokens

### ISSUE THREAD

**Issue by dancerphil** [dancerphil/antd-v5-theme-converter#1]
## 为什么起草这个RFC？

使得组件的样式覆盖更加简便，并且可以跳过 css 权重带来的影响

## APIs

1. 在组件最终生成 css 时，采用先定义再引用的方式，这样，浏览器中会显示变量名称，更具备可读性：

```css
.ant-btn-primary-hashed {
	--btn-color-primary: blue;

	background-color: var(--btn-color-primary);
}
```

2. 用户使用 className 覆盖时，可以采用更加语义化的方式覆盖 css variables，以下举例了一个 css-in-js 方案，css 方案同理：

```javascript
const ButtonDanger = styled(Button)`
	--btn-color-primary: red;
`
```

## 一些额外说明和设计

1. Final Token 具备局域性，都会具备组件的前缀，比如 `--btn-color-xxx`, `--modal-background-color-xxx`

2. 采用该方式后，一些组件可以很方便的复用：
<img width="539" alt="image" src="https://user-images.githubusercontent.com/7264444/196166367-a36b6de9-98a6-4f6c-bf4b-74cb2f692ad1.png">
